<?php
/**
 * 
 * NOTICE OF LICENSE
 *
 * This source file is released and licensed under a limited, non-exclusive and non-assignable commercial license by Lemonline. 
 *
 * @category   Lemonline
 * @package    Lemonline_SVMPaymentModule
 * @copyright  Copyright (c) 2012 Lemonline (http://www.lemonline.fi)
 * @license    http://www.lemonline.fi/licenses/lemonline-license-1.0.txt  Lemonline License
 */

?>

Method