<?php
/**
 * YOU ARE USING FREE EXTENSION, THERE ARE POWERED LINKS IN BLOG FOOTER. YOU SHOULD KEEP THESE LINKS TO HELP US.
 * THANK YOU!
 */
?>
<div class="mp-footer"> <span class="mp-footer-links-light"> <h3> <a href="https://www.mageplaza.com/magento-2-blog-extension/">Magento 2 Blog</a> powered by <a href="https://www.mageplaza.com/kb/magento-2-tutorial/" target="_blank">Tutorial</a> <a href="https://www.mageplaza.com/magento-2-extensions/" target="_blank">Magento 2 extensions</a> <a href="https://www.mageplaza.com/" target="_blank">Mageplaza</a> </h3> </span> </div>