<?php
/**
 * How to call in CMS page
 * {{block type='mageplaza_betterblog/post_recent'  post_count="1" block_name="Latest from the blog" template='mageplaza_betterblog/post/recent.phtml'}}
 * {{block type='mageplaza_betterblog/post_cat'  post_count="1" category_id="4" block_name="Latest news" template='mageplaza_betterblog/post/recent.phtml'}}
 */
?>


<?php $posts = $this->getPosts(); ?>
<?php $postCount = $this->getPostCount(); ?>
<?php $i=0; ?>

<div id="frontpage-recent-posts">

    <div class="feature">
        <h7><?php echo $this->getBlockName();?></h7>
        <?php foreach ($posts as $post): ?>
            <?php 
            if($i >= $postCount) break;
            $stamp = date("j.n.", strtotime($post->getTapahtumanPvm()));
            ?>
<!--            <div class="post-image">
                <?php /*if ($post->getImage()) :*/?>
                    <img src="<?php /*echo Mage::helper('mageplaza_betterblog/post_image')->init($post, 'image');*/?>" alt="<?php /*echo $this->escapeHtml($post->getPostTitle());*/?>" />
                <?php /*endif;*/?>
            </div>-->
            <br>

            <div class="post-list-item">
                <a href="<?php echo $post->getPostUrl(); ?>" ><?php echo $stamp . '&nbsp;' . $post->getPostTitle(); ?></a>
            </div>
<!--            <div class="post-short-description">
                <p><?php /*echo $post->getPostExcerpt();*/?></p>
            </div>-->
            <?php $i++; ?>
        <?php endforeach; ?>

        <div class="archieve"><a href="uutiset">Uutisarkisto &gt;&gt;</a></div>
    </div>

</div>
